// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EliMZ_Book","status":true,"description":"♦5.4.17♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"styleOverflow\":\"false\",\"--- MZ ONLY ---\":\"\",\"disableEffekseer\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"ScreenZoom","status":true,"description":"[Ver1.1.1]Zoom screen whose center is specified character or player.","parameters":{}},
{"name":"EliMZ_Zoom","status":true,"description":"♦1.3.0♦ Add the default zoom feature to plugin command.","parameters":{"persistentZoomSw":"0"}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"Luna_QPlus","status":true,"description":"Some small changes to MV for easier plugin development.\n<Luna_QPlus>","parameters":{"Quick Test":"false","Default Enabled Switches":"[]","Ignore Mouse when inactive":"false"}},
{"name":"Luna_QMovement","status":true,"description":"Add more control over your character with pixel movement\n<Luna_QMovement>","parameters":{"Main Settings":"","Grid":"1","Tile Size":"48","Off Grid":"true","Optional Settings":"","Smart Move":"2","Mid Pass":"false","Move on click":"true","Diagonal":"true","Diagonal Speed":"0","Colliders":"","Player Collider":"{\"Type\":\"box\",\"Width\":\"36\",\"Height\":\"24\",\"Offset X\":\"6\",\"Offset Y\":\"24\"}","Event Collider":"{\"Type\":\"box\",\"Width\":\"36\",\"Height\":\"24\",\"Offset X\":\"6\",\"Offset Y\":\"24\"}","Presets":"[]","Debug Settings":"","Show Colliders":"false"}},
{"name":"Luna_QCollisionMap","status":true,"description":"QMovement Addon: Adds image collision maps\r\n<Luna_QMCollisionMap>","parameters":{"Scan Size":"4","Folder":"img/collisions/"}}
];
